version: '3.4'
networks:
  my-app-network:
    driver: bridge

services:
  exam.mvc:
    image: ${DOCKER_REGISTRY-}exammvc
    build:
      context: ./Exam.MVC   
      dockerfile: Dockerfile
    networks:
      - my-app-network
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Qwerty@12"
    networks:
      - my-app-network
    volumes:
      - sql_data:/var/opt/mssqlserver

  elasticsearch:
    image: elasticsearch:8.14.3
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    networks:
      - my-app-network
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/datas
  kibana:
   image: kibana:8.14.3
   ports:
    - 5601:5601
   environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200

volumes:
  elasticsearch-data:
  sql_data:
    driver: local
