version: '3.4'

services:
  exam.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ExamDb;User Id=sa;Password=Qwerty@12;TrustServerCertificate=True;
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - my-app-network
  sqlserver:
    ports:
      - "1433:1433"
    networks:
      - my-app-network
  elasticsearch:
    ports:
      - 9200:9200
    networks:
      - my-app-network
  kibana:
   ports:
    - 5601:5601
   networks:
      - my-app-network