version: '3.4'
networks:
  my-app-network:
    driver: bridge

services:
  exam.mvc:
    image: ${DOCKER_REGISTRY-}exammvc
    build:
      context: ./Exam.MVC   
      dockerfile: Dockerfile
    networks:
      - my-app-network
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Qwerty@12"
    networks:
      - my-app-network
    volumes:
      - sql_data:/var/opt/mssqlserver
volumes:
  sql_data:
    driver: local

